language: java
install: skip

os: linux
dist: trusty
jdk: oraclejdk14

before_install:
  - nvm install v14.15.5
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.4.2/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

script:
  - ./gradlew clean build
  - ./gradlew :airbyte-tests:acceptanceTests
