language: java
install: skip

os: linux
dist: focal
jdk: oraclejdk14

services:
  - docker

before_install:
  - nvm install v14.15.5

script:
  - ./gradlew clean build
  - ./gradlew :airbyte-tests:acceptanceTests
